### ISSUE TITLE
JSON Validation with JSON Reads[T] 

### ISSUE THREAD

**Issue by AvramRobert** [FHK-ADV/lwm-reloaded#6]
Link: https://www.playframework.com/documentation/2.1.1/ScalaJsonCombinators

Ich habe das heute gefunden und mal durchgelesen und finde es wirklich interessant. Damit haben wir einen Aggregat zwischen einem JSON Parser und Validator. Sieht auch relativ elegant aus. 
Es gibt auch eine "enhanced" Version mit Macros die schöner ausseiht, aber ich weiß nicht wie stabil sie ist.

Ich denke, dass dieses Ding auch unsere MIME Types ersetzen könnte.

**Comment by lichtsprung** [comment]
Ja, wir werden die Reads und Writes verwenden ;)

**Comment by AvramRobert** [comment]
Marvelous!
